In [1]:
import databento as db

client = db.Historical(key="db-7wW8CmBW3acSrST5TndWvAM6keexJ")
data = client.timeseries.get_range(
    dataset="XNAS.ITCH",
    schema="mbp-10",
    symbols=["MSFT"],
    start="2026-05-05T13:30",     # 09:30 ET in UTC
    end="2026-05-05T20:00",       # 16:00 ET in UTC
    stype_in="raw_symbol",
)
df = data.to_df()                  # already nanosecond-precision pandas

In [13]:
df.reset_index(inplace=True)

In [24]:
df[(df["side"]!="N")&(df["action"]=="T")].iloc[100:120]

,ts_recv,ts_event,rtype,publisher_id,instrument_id,action,side,depth,price,size,...,ask_sz_08,bid_ct_08,ask_ct_08,bid_px_09,ask_px_09,bid_sz_09,ask_sz_09,bid_ct_09,ask_ct_09,symbol
663,2026-05-05 13:30:01.322476932+00:00,2026-05-05 13:30:01.322304572+00:00,10,2,10888,T,B,0,415.30,40,...,12,2,1,415.02,415.78,8,845,1,1,MSFT
666,2026-05-05 13:30:01.322775725+00:00,2026-05-05 13:30:01.322598302+00:00,10,2,10888,T,B,0,415.35,100,...,845,2,1,415.02,415.79,8,100,1,1,MSFT
667,2026-05-05 13:30:01.322775725+00:00,2026-05-05 13:30:01.322598302+00:00,10,2,10888,T,B,0,415.35,20,...,845,2,1,415.02,415.79,8,100,1,1,MSFT
668,2026-05-05 13:30:01.322775725+00:00,2026-05-05 13:30:01.322598302+00:00,10,2,10888,T,B,0,415.35,15,...,845,2,1,415.02,415.79,8,100,1,1,MSFT
669,2026-05-05 13:30:01.322775725+00:00,2026-05-05 13:30:01.322598302+00:00,10,2,10888,T,B,0,415.35,33,...,845,2,1,415.02,415.79,8,100,1,1,MSFT
747,2026-05-05 13:30:01.390801669+00:00,2026-05-05 13:30:01.390630507+00:00,10,2,10888,T,B,0,415.35,11,...,100,2,1,415.00,415.80,525,100,23,1,MSFT
795,2026-05-05 13:30:01.557458926+00:00,2026-05-05 13:30:01.557288777+00:00,10,2,10888,T,B,0,415.35,23,...,100,1,1,414.96,415.80,161,200,2,2,MSFT
797,2026-05-05 13:30:01.557498615+00:00,2026-05-05 13:30:01.557317917+00:00,10,2,10888,T,B,0,415.35,33,...,100,1,1,414.96,415.80,161,200,2,2,MSFT
798,2026-05-05 13:30:01.557498615+00:00,2026-05-05 13:30:01.557317917+00:00,10,2,10888,T,B,0,415.35,40,...,100,1,1,414.96,415.80,161,200,2,2,MSFT
799,2026-05-05 13:30:01.557498615+00:00,2026-05-05 13:30:01.557317917+00:00,10,2,10888,T,B,0,415.35,47,...,100,1,1,414.96,415.80,161,200,2,2,MSFT
852,2026-05-05 13:30:01.748750085+00:00,2026-05-05 13:30:01.748580618+00:00,10,2,10888,T,B,0,415.35,8,...,100,5,1,415.00,415.80,525,200,23,2,MSFT
879,2026-05-05 13:30:01.748912423+00:00,2026-05-05 13:30:01.748742534+00:00,10,2,10888,T,B,0,415.38,3,...,200,2,2,415.05,415.83,153,12,2,1,MSFT
893,2026-05-05 13:30:01.748991498+00:00,2026-05-05 13:30:01.748821554+00:00,10,2,10888,T,B,0,415.40,1,...,12,2,1,415.09,416.00,120,544,1,4,MSFT
894,2026-05-05 13:30:01.748991498+00:00,2026-05-05 13:30:01.748821554+00:00,10,2,10888,T,B,0,415.41,8,...,544,2,4,415.09,416.05,120,80,1,1,MSFT
947,2026-05-05 13:30:01.750005042+00:00,2026-05-05 13:30:01.749830510+00:00,10,2,10888,T,B,0,415.50,1,...,80,2,1,415.19,416.10,133,9,2,2,MSFT
1008,2026-05-05 13:30:01.804946869+00:00,2026-05-05 13:30:01.804777277+00:00,10,2,10888,T,B,0,415.50,1,...,80,1,1,415.13,416.10,160,9,2,2,MSFT
1009,2026-05-05 13:30:01.804946869+00:00,2026-05-05 13:30:01.804777277+00:00,10,2,10888,T,B,0,415.50,2,...,80,1,1,415.13,416.10,160,9,2,2,MSFT
1015,2026-05-05 13:30:01.804952312+00:00,2026-05-05 13:30:01.804777277+00:00,10,2,10888,T,B,0,415.55,19,...,9,1,2,415.13,416.12,160,4,2,1,MSFT
1036,2026-05-05 13:30:01.805062335+00:00,2026-05-05 13:30:01.804892656+00:00,10,2,10888,T,B,0,415.60,184,...,9,2,2,415.25,416.12,153,4,3,1,MSFT
1039,2026-05-05 13:30:01.805084484+00:00,2026-05-05 13:30:01.804913518+00:00,10,2,10888,T,B,0,415.60,28,...,9,2,2,415.25,416.12,153,4,3,1,MSFT

In [35]:
df[(df["action"]=="T")&(df["side"]!="N")]

,ts_recv,ts_event,rtype,publisher_id,instrument_id,action,side,depth,price,size,...,ask_sz_08,bid_ct_08,ask_ct_08,bid_px_09,ask_px_09,bid_sz_09,ask_sz_09,bid_ct_09,ask_ct_09,symbol
2,2026-05-05 13:30:00.006313494+00:00,2026-05-05 13:30:00.006128597+00:00,10,2,10888,T,B,0,415.19,110,...,5,2,1,414.85,416.24,9,5,3,1,MSFT
4,2026-05-05 13:30:00.008292687+00:00,2026-05-05 13:30:00.008124461+00:00,10,2,10888,T,B,0,415.19,170,...,5,2,1,414.85,416.24,9,5,3,1,MSFT
38,2026-05-05 13:30:00.179713946+00:00,2026-05-05 13:30:00.179538764+00:00,10,2,10888,T,A,0,415.12,200,...,213,2,3,414.85,416.20,9,230,3,2,MSFT
48,2026-05-05 13:30:00.181291715+00:00,2026-05-05 13:30:00.181120236+00:00,10,2,10888,T,A,0,415.10,10,...,100,3,1,414.82,415.80,600,310,1,3,MSFT
49,2026-05-05 13:30:00.181291715+00:00,2026-05-05 13:30:00.181120236+00:00,10,2,10888,T,A,0,415.10,5,...,100,3,1,414.82,415.80,600,310,1,3,MSFT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1233887,2026-05-05 19:59:59.899660763+00:00,2026-05-05 19:59:59.899485207+00:00,10,2,10888,T,A,0,411.27,78,...,17,3,2,411.18,411.44,1949,80,2,1,MSFT
1233888,2026-05-05 19:59:59.899660763+00:00,2026-05-05 19:59:59.899485207+00:00,10,2,10888,T,A,0,411.27,145,...,17,3,2,411.18,411.44,1949,80,2,1,MSFT
1233889,2026-05-05 19:59:59.899660763+00:00,2026-05-05 19:59:59.899485207+00:00,10,2,10888,T,A,0,411.27,1800,...,17,3,2,411.18,411.44,1949,80,2,1,MSFT
1233890,2026-05-05 19:59:59.899660763+00:00,2026-05-05 19:59:59.899485207+00:00,10,2,10888,T,A,0,411.27,5,...,17,3,2,411.18,411.44,1949,80,2,1,MSFT
1233897,2026-05-05 19:59:59.900356456+00:00,2026-05-05 19:59:59.900188532+00:00,10,2,10888,T,A,0,411.27,46,...,17,2,2,411.15,411.44,16363,80,6,1,MSFT

In [36]:
idx = 38
df.iloc[idx-5:idx+5, :17]

,ts_recv,ts_event,rtype,publisher_id,instrument_id,action,side,depth,price,size,flags,ts_in_delta,sequence,bid_px_00,ask_px_00,bid_sz_00,ask_sz_00
33,2026-05-05 13:30:00.173039243+00:00,2026-05-05 13:30:00.172867077+00:00,10,2,10888,A,A,1,415.36,8,128,172166,47269320,415.12,415.28,200,200
34,2026-05-05 13:30:00.173060380+00:00,2026-05-05 13:30:00.172890382+00:00,10,2,10888,A,A,0,415.28,40,128,169998,47269342,415.12,415.28,200,240
35,2026-05-05 13:30:00.173529107+00:00,2026-05-05 13:30:00.173359684+00:00,10,2,10888,T,N,0,415.15,100,128,169423,47269711,415.12,415.28,200,240
36,2026-05-05 13:30:00.178200182+00:00,2026-05-05 13:30:00.178032567+00:00,10,2,10888,T,N,0,415.15,100,128,167615,47273223,415.12,415.28,200,240
37,2026-05-05 13:30:00.179696741+00:00,2026-05-05 13:30:00.179528865+00:00,10,2,10888,A,A,1,415.32,8,128,167876,47274672,415.12,415.28,200,240
38,2026-05-05 13:30:00.179713946+00:00,2026-05-05 13:30:00.179538764+00:00,10,2,10888,T,A,0,415.12,200,0,175182,47274693,415.12,415.28,200,240
39,2026-05-05 13:30:00.179713946+00:00,2026-05-05 13:30:00.179538764+00:00,10,2,10888,C,B,0,415.12,200,128,175182,47274693,415.10,415.28,16,240
40,2026-05-05 13:30:00.179756056+00:00,2026-05-05 13:30:00.179581584+00:00,10,2,10888,A,A,0,415.27,15,128,174472,47274752,415.10,415.14,16,100
41,2026-05-05 13:30:00.179763717+00:00,2026-05-05 13:30:00.179594294+00:00,10,2,10888,C,A,4,415.28,40,128,169423,47274763,415.10,415.14,16,100
42,2026-05-05 13:30:00.179765740+00:00,2026-05-05 13:30:00.179596235+00:00,10,2,10888,A,A,1,415.28,40,128,169505,47274768,415.10,415.14,16,100